name: audio-transcriber
channels:
  - conda-forge
dependencies:
  - python=3.10.18
  - ffmpeg
  - pip
  - python-dotenv
  - pip:
    - torch                
    - openai-whisper       # Whisper inference
    - tqdm                 # progress bars
    - pyannote.audio       # speaker diarization
